server:
  error:
    path: /error
#    whitelabel:
#      enabled: false

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${PORTAL_MAIL_USERNAME:fake.user@gmail.com}
    password: ${PORTAL_MAIL_PASSWORD:fake_password}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/support-portal
    username: ENC(bGNdXu0n1sQxtHpAQy8E/fegT25zKbk6iTZoqg8ddaU=)
    password: ENC(hZarzMkUMf97sQ07tD58A2HOhbdoPdZtcpkif4vR9jY=)
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
app:
  public-urls: /user/login,/user/register,/user/*/profile-image/**
  cors:
    allowed-origins: http://localhost:4200,https://localhost:4200,http://art-support-portal.s3-website.eu-north-1.amazonaws.com,http://portal.shyshkin.net
  jwt:
    secret: ENC(VAMFn7FEkahKbzf+99EzkajMeLjE/WvJLCadLVZXSE8=)
#    secret: ${random.value} #Does not work - every time generates new value
jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:23306/support-portal
  jpa:
    show-sql: true
logging:
  level:
    net.shyshkin: debug

---
spring:
  config:
    activate:
      on-profile: aws-local
  datasource:
    url: jdbc:mysql://localhost:3306/support_portal
    username: support_portal_user
    password: Supp0rt_Porta!_P@ssword
  mail:
    host: email-smtp.eu-north-1.amazonaws.com
    port: 587
    username: AKIAVW7XGDOWFHHCELIH
    password: BJyWOWS1xWYR35MRCFn3BuuQ6vY+k7DRsdAvOfqDs/Fk

# we want to test (1) from localhost, (2) from S3 bucket Static Web Site, (3) from our EC2 instance
app:
  email:
    from: d.art.shishkin@gmail.com
    carbon-copy: d.art.shishkin@gmail.com
  cors:
    allowed-origins: http://localhost:4200,http://art-support-portal.s3-website.eu-north-1.amazonaws.com,http://support-portal.shyshkin.net,http://portal.shyshkin.net
server:
  port: 5000
logging:
  level:
    net.shyshkin: debug

---
spring:
  config:
    activate:
      on-profile: aws-rds
  datasource:
    url: jdbc:mysql://portal-db.coaum9neetxc.eu-north-1.rds.amazonaws.com:3306/support_portal
    username: ENC(35q85d0/Lei1FAWM5zvqUyfnOxvUYqWG)
    password: ENC(IN86fPa4xxATIP1S5fV94fos3drWXOTCurStNvQYM9s=)
  mail:
    host: email-smtp.eu-north-1.amazonaws.com
    port: 587
    username: ENC(WWVCoLPOjjNlfepTKeRFF4wep6onc3LnbkoPGh+Xwqc=)
    password: ENC(VTO/7U6tFHSzMs6UtTusUXSWAUkgLaTbsqvsVphIvCS9VfdEd9nx8+919i7usoKwvuzWZPFx4/8=)

# we want to test (1) from localhost, (2) from S3 bucket Static Web Site, (3) from our EC2 instance
app:
  email:
    from: d.art.shishkin@gmail.com
    carbon-copy: d.art.shishkin@gmail.com
  cors:
    allowed-origins: http://localhost:4200,http://art-support-portal.s3-website.eu-north-1.amazonaws.com,http://support-portal.shyshkin.net,http://portal.shyshkin.net
server:
  port: 5000
logging:
  level:
    net.shyshkin: debug

#####
#
# HTTPS configuration
#
#####

server.ssl:
  enabled: true               # Enable HTTPS support (only accept HTTPS requests)
  key-alias: securedPortal         # Alias that identifies the key in the key store
  key-store: classpath:securedPortal-keystore.p12  # Keystore location
  key-store-password: ENC(WNuqkduFC9d7bjWwv+KqKA==)  # Keystore password
  key-store-type: PKCS12      # Keystore format

---
spring:
  config:
    activate:
      on-profile: image-s3
app:
  amazon-s3:
    bucket-name: portal-user-profile-images



